# Generated by Django 5.2.8 on 2025-11-09 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_contacto",
                    models.CharField(max_length=200, verbose_name="Nombre de contacto"),
                ),
                (
                    "email_contacto",
                    models.EmailField(max_length=254, verbose_name="Email de contacto"),
                ),
                (
                    "telefono_contacto",
                    models.CharField(
                        max_length=20, verbose_name="Teléfono de contacto"
                    ),
                ),
                (
                    "nombre_empresa",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nombre de empresa/organización",
                    ),
                ),
                (
                    "nombre_evento",
                    models.CharField(max_length=300, verbose_name="Nombre del evento"),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripción del evento"),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(verbose_name="Fecha y hora de inicio"),
                ),
                (
                    "fecha_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha y hora de fin"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("deportivo", "Deportivo"),
                            ("cultural", "Cultural"),
                            ("salud", "Salud y Bienestar"),
                            ("recreativo", "Recreativo"),
                            ("educativo", "Educativo"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "tipo_entrada",
                    models.CharField(
                        choices=[("gratuito", "Gratuito"), ("pago", "De Pago")],
                        default="gratuito",
                        max_length=20,
                        verbose_name="Tipo de entrada",
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio (si aplica)",
                    ),
                ),
                (
                    "url_evento",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL del evento"
                    ),
                ),
                (
                    "imagen_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL de imagen del evento"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(max_length=500, verbose_name="Dirección"),
                ),
                ("ciudad", models.CharField(max_length=100, verbose_name="Ciudad")),
                (
                    "latitud",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Latitud"
                    ),
                ),
                (
                    "longitud",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Longitud"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_solicitud",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de solicitud"
                    ),
                ),
                (
                    "fecha_respuesta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de respuesta"
                    ),
                ),
                (
                    "comentarios_admin",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Comentarios del administrador",
                    ),
                ),
                (
                    "respondido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_requests_respondidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Respondido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Evento",
                "verbose_name_plural": "Solicitudes de Eventos",
                "ordering": ["-fecha_solicitud"],
            },
        ),
    ]
