# Generated by Django 5.2.6 on 2025-11-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='codigo_seguimiento',
            field=models.CharField(blank=True, db_index=True, help_text='Código único para consultar el estado de la solicitud', max_length=20, null=True, unique=True, verbose_name='Código de seguimiento'),
        ),
    ]
