# Generated by Django 5.2.6 on 2025-10-19 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('caminar', 'Caminar'), ('correr', 'Correr'), ('bicicleta', 'Bicicleta'), ('gimnasio', 'Gimnasio'), ('otro', 'Otro')], max_length=30)),
                ('duracion_min', models.PositiveIntegerField()),
                ('calorias', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fecha', '-creado'],
            },
        ),
    ]
