# Generated by Django 5.2.6 on 2025-11-23 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_actual', models.FloatField(help_text='Peso actual en kg')),
                ('peso_objetivo', models.FloatField(help_text='Peso objetivo en kg')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_objetivo', models.DateField(help_text='Fecha para alcanzar el objetivo')),
                ('nivel_actividad', models.CharField(choices=[('sedentario', 'Sedentario (poco o ningún ejercicio)'), ('ligero', 'Ligero (ejercicio 1-3 días/semana)'), ('moderado', 'Moderado (ejercicio 3-5 días/semana)'), ('activo', 'Activo (ejercicio intenso 6-7 días/semana)'), ('muy_activo', 'Muy Activo (ejercicio intenso diario o doble sesión)')], default='sedentario', max_length=20)),
                ('activo', models.BooleanField(default=True, help_text='Si es False, la meta está archivada/completada')),
                ('tmb', models.FloatField(blank=True, help_text='Tasa Metabólica Basal', null=True)),
                ('get', models.FloatField(blank=True, help_text='Gasto Energético Total', null=True)),
                ('deficit_diario', models.FloatField(blank=True, help_text='Déficit/Superávit calórico diario requerido', null=True)),
                ('meta_calorica_diaria', models.FloatField(blank=True, help_text='Meta calórica diaria', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_peso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta de Peso',
                'verbose_name_plural': 'Metas de Peso',
                'ordering': ['-activo', '-created_at'],
            },
        ),
    ]
