# Generated by Django 5.2.6 on 2025-11-11 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='foto',
        ),
    ]
